---
title: "git_01"
author: "Heather Hobmeier"
date: "Sept 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Twas brilling, and the slitghy toves
Did gyre and gimble in the wabe
Allmimsy were the borogoves,
Ans the mome raths outgrambe
  
Beware the Jabberwock, my son!
The jaws that bite, the claws that catch!
Beware the Jubjub bird, and shun
The frumious Bandersnatch!>

## Second Verse
<Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear;
Though as for that the passing there
Had worn them really about the same>

## Third Verse
<The sun was shining on the sea, 
      Shining with all his might: 
He did his very best to make 
      The billows smooth and bright — 
And this was odd, because it was 
      The middle of the night. 

The moon was shining sulkily, 
      Because she thought the sun 
Had got no business to be there 
      After the day was done — 
"It's very rude of him," she said, 
      "To come and spoil the fun>

## Last Verse
<When you lay awake in bed at night,
trying to give yourself over to sleep..
Yet, your mind refuses
to give into the darkness
Surrounding and consuming all in its path

It shoots bits of light out
In form or imagination
Memories
And What-ifs

It leaves you stranded
Stuck somewhere
Between conscious thought,
A restful, blank mind,
And the good/bad thoughts of the future

It's a love triangle of sorts
But a peaceful one
For the object of intention is rarely harmed
You just peacefully give into one of the three
Each night night be a different one
Who knows,
Maybe you want to sample each..?

But for some we have picked two favorites
Cast out one and let the others pull us in half
Quite literally held over a chasm in your mind
Sleep or Thought?

Sleep is so peaceful,
It can bring about such wonderful dreams
But it can also bring nightmares
Or else just blank, empty darkness
A gamble you are always willing to take

Thoughts lead to discovery
Some of the hardest problems can be solved late at night.
Thoughts can also lead to new questions
Does he like me like I like him?
Should I buy this or that?
What should I do for class tomorrow?
Questions like these....

Some we answer immediately
Others we lay there and ponder

It is a constant struggle
Between sweet, velvety soft darkness
And
Sharp, imaginative thoughts
Which one will win?>
